package de.fkoeberle.autocommit.message.java;

public enum BodyDeclarationChangeType {
	MODIFIERS, JAVADOC, DECLARATION_LIST, SUPER_CLASS, SUPER_INTERFACE_LIST, TYPE_OF_TYPE, RETURN_TYPE, METHOD_BODY, METHOD_EXTRA_DIMENSIONS, FIELD_TYPE;
}
